pipeline:
  name: Secure Build and Deploy
  identifier: Secure_Build_and_Deploy
  projectIdentifier: Platform_Engineering
  orgIdentifier: demo
  tags:
    owner: DemoCommittee
    iacmManaged: "true"
  properties:
    ci:
      codebase:
        repoName: org.devsecops
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Test
                  name: Test Intelligence
                  identifier: Test_Intelligence
                  spec:
                    shell: Sh
                    command: |-
                      cd ./python-tests
                      pytest
                    intelligenceMode: true
              - step:
                  name: Compile
                  identifier: Compile
                  template:
                    templateRef: org.Compile_Application
                    versionLabel: "1.0"
              - parallel:
                  - step:
                      type: Owasp
                      name: OWASP
                      identifier: OWASP
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                      when:
                        stageStatus: Success
                  - step:
                      type: OsvScanner
                      name: OSV Scan
                      identifier: OSV_Scan
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                      when:
                        stageStatus: Success
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Push to Dockerhub
                  identifier: Push_to_Dockerhub
                  spec:
                    connectorRef: account.harnessImage
                    repo: seworkshop/devsecops-demo
                    tags:
                      - 0.0.<+pipeline.sequenceId>
                    dockerfile: /harness/frontend-app/harness-webapp/Dockerfile
                    context: /harness/frontend-app/harness-webapp
              - parallel:
                  - step:
                      type: Background
                      name: dind
                      identifier: dind
                      spec:
                        connectorRef: account.harnessImage
                        image: docker:dind
                        shell: Sh
                  - step:
                      type: AquaTrivy
                      name: Aqua Trivy
                      identifier: Aqua_Trivy
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: container
                          detection: auto
                        advanced:
                          log:
                            level: info
                        privileged: true
                        image:
                          type: docker_v2
                          name: seworkshop/devsecops-demo
                          tag: 0.0.<+pipeline.sequenceId>
                        sbom:
                          format: spdx-json
    - stage:
        name: Frontend - Deployment
        identifier: Frontend_Deployment
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: org.DevSecOps_Frontend
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: org.dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devsecops
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - parallel:
        - stage:
            name: Backend - Deployment
            identifier: Backend_Deployment
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: org.DevSecOps_Backend
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
              environment:
                useFromStage:
                  stage: Frontend_Deployment
              execution:
                steps:
                  - stepGroup:
                      name: Canary Deployment
                      identifier: canaryDeployment
                      steps:
                        - step:
                            name: Canary Deployment
                            identifier: canaryDeployment
                            type: K8sCanaryDeploy
                            timeout: 10m
                            spec:
                              instanceSelection:
                                type: Count
                                spec:
                                  count: 1
                              skipDryRun: false
                        - step:
                            type: Verify
                            name: Verify
                            identifier: Verify
                            spec:
                              isMultiServicesOrEnvs: false
                              type: Canary
                              monitoredService:
                                type: Default
                                spec: {}
                              spec:
                                sensitivity: LOW
                                duration: 5m
                            timeout: 2h
                            failureStrategies:
                              - onFailure:
                                  errors:
                                    - Verification
                                  action:
                                    type: ManualIntervention
                                    spec:
                                      timeout: 2h
                                      onTimeout:
                                        action:
                                          type: StageRollback
                              - onFailure:
                                  errors:
                                    - Unknown
                                  action:
                                    type: ManualIntervention
                                    spec:
                                      timeout: 2h
                                      onTimeout:
                                        action:
                                          type: Ignore
                            when:
                              stageStatus: Success
                        - step:
                            name: Canary Delete
                            identifier: canaryDelete
                            type: K8sCanaryDelete
                            timeout: 10m
                            spec: {}
                  - stepGroup:
                      name: Primary Deployment
                      identifier: primaryDeployment
                      steps:
                        - step:
                            name: Rolling Deployment
                            identifier: rollingDeployment
                            type: K8sRollingDeploy
                            timeout: 10m
                            spec:
                              skipDryRun: false
                rollbackSteps:
                  - step:
                      name: Canary Delete
                      identifier: rollbackCanaryDelete
                      type: K8sCanaryDelete
                      timeout: 10m
                      spec: {}
                  - step:
                      name: Rolling Rollback
                      identifier: rollingRollback
                      type: K8sRollingRollback
                      timeout: 10m
                      spec: {}
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: DAST Scans
            identifier: DAST_Scans
            template:
              templateRef: org.DAST_Scans
              versionLabel: "2.0"
  description: https://devsecops.harness-demo.site
